all: show-bytes bits sum_elements longer_string

clean:
	@echo "deleting executables"
	@rm -f *.o

show-bytes: show-bytes.c
	gcc -o show-bytes.o show-bytes.c
bits: bits.c
	gcc -o bits.o bits.c
sum_elements: sum_elements.c
	gcc -o sum_elements.o sum_elements.c
longer_string: longer_string.c
	gcc -o longer_string.o longer_string.c
uadd_ok: uadd_ok.c
	gcc -o uadd_ok.o uadd_ok.c
tadd_ok: tadd_ok.c
	gcc -o tadd_ok.o tadd_ok.c
tsub_ok: tsub_ok.c
	gcc -o tsub_ok.o tsub_ok.c
